watford_occurances = [
    "Keeper gives the ball away",
    "A wide defender passes backwards despite an attacker running in behind",
    "A holding defender makes a backwards pass despite many forward options",
    "A player gets a yellow card for a 'stupid' tackle",
    "Watford are leading the game but throw it away",
    "On a promising counter attack a player passes backwards",
    "On a promising counter attack a player stands on the ball",
    "No player makes a cross despite spending over 30 seconds near the corner flag of the opposing team",
    "Rather than booting the ball away from danger we try to pass it out and fail",
    "We have a player rolling on the ground after a seemingly fair tackle",
    "A striker doesnt even challenge for the ball",
    "Pedro choses to try it alone and fails",
    "Our striker comes to pick the ball up from our defenders",
    "We go behind within 10 minutes",
    "We keep a clean sheet",
    "We are 3 goals up",
    "We give away a silly free kick on the edge of our area",
    "We hit first man from a corner",
    "We send the ball straight to the keeper from a corner",
    "We send the ball miles over the box from a corner",
    "We pass short from a corner",
    "We let in a goal from a counter attack from a corner",
    "We score and own goal",
    "CB is beaten to a header",
    "Manager sacked during the game",
    "We give away a free header from a corner",
    "Two balls on the field at once",
    "Player goes off with hamstring injury",
]
